### PR TITLE
Configure acend ingress to use wildcard cert

### PR DESCRIPTION
**Pull request by phil-pona**

### CODE REVIEW

**Comment by bliemli** [comment]
Where does the `acend-wildcard` secret come from?

**Comment by phil-pona** [comment]
It's magic ;-) no jokes aside. We've hit the rate limit so @splattner deployed an acend wildcard cert for *.training.acend.ch The secret is managed through https://appscode.com/products/kubed/v0.12.0/guides/config-syncer/intra-cluster/
@splattner correct me if I'm wrong

**Comment by bliemli** [comment]
We can't yet switch, the certificate is not yet ready:

```
Warning  Failed   6m43s (x129 over 5d8h)  cert-manager  The certificate request has failed to complete and will be retried: Failed to wait for order resource "acend-wildcard-2qpkr-3085140742" to become ready: order is in "errored" state: Failed to create Order: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates already issued for: acend.ch: see https://letsencrypt.org/docs/rate-limits/
```

But anyways, @splattner , wouldn't it be easier to configure the wildcard certificate on the ingress controller and simply use edge ingresses? This way no secret has to be synchronized between namespaces which means we have another component out of the picture which could fail.

**Comment by bliemli** [comment]
Secrets are now synchronised.

**Review by bliemli — APPROVED** [review]

**Pull request merged**
